# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: c

env:
  global:
    - GITHUB_RELEASE_FILE = ./_build/fakepackage_0.1.1.tar.gz

before_install:
  - curl -OL http://raw.github.com/luckyrandom/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
install:
  - ./travis-tool.sh install_deps
script: ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

after_success:
  - ./travis-tool.sh build_pkg
  - ./travis-tool.sh deploy

notifications:
  email:
    on_success: change
    on_failure: change

deploy:
  provider: releases
  api_key:
    secure: j88u99CWhMfa2kFBbD/F1p9Cg8FKRHZ65UVpQQ9T8J/5kYXU0D3KppLvGW+MaTfbYdzaU44/BFXfxSWs0FbpPNGuNNJn3GBhFtmx1fwgJUX6SS12wcHbL9Qn2wT2vWWKZtyguavr2DvH7xwd1pT0pEo6Y8YY5Q5gMTmmoSAWBYI=
  file: ${GITHUB_RELEASE_FILE}
  on:
    repo: luckyrandom/test-r-travis
    tags: true
    all_branches: true